spring.application.name: dump-screener
screener:
  stableCoins: USDT,USDC
  cexes: BINANCE
  networks: ETHEREUM
  cryptoCompare:
    apiKey: 0ad56d567c3724cce20251382c73a67384759e3726258c89efe489f392d0e52d
  coingeco:
    apiKey: CG-9rRie9kn3qe7nBraTf734zYV
  oneinch:
    apiKey:
  volume24h: 1000000
  marketCap: 1000000
  detectRate: 1440000
  screeningRate: 20000
  rules:
    - dumpPeriod: 30000
      triggerPercentage: 10