spring:
  application:
    name: dump-screener
  main:
    banner-mode: off
screener:
  stableCoins: USDT,USDC,FDUSD
  cexes: BINANCE,KUCOIN,GATE,OKX,BITMART,HUOBI
  networks: ETHEREUM
  maxAllowedPriceChangePercentage: 70
  metadataUpdateRateSec: 86400
  screeningRateSec: 10
  initialDelaySec: 90
  cryptoCompare:
    apiKey: ${CRYPTO_COMPARE_API_KEY}
  coingecko:
    apiKey: ${COIN_GECKO_API_KEY}
  oneinch:
    apiKey: ${ONE_INCH_API_KEY}

telegram:
  apiToken: ${TELEGRAM_BOT_TOKEN}
  notificationChatId: ${TELEGRAM_NOTIFICATION_CHANNEL_ID}
